# Generated by Django 5.2.17 on 2026-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_id",
                    models.PositiveBigIntegerField(verbose_name="رقم مركز الشباب"),
                ),
                (
                    "facility_name",
                    models.CharField(max_length=100, verbose_name="مركز الشباب"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("report", "شكوى"), ("recommendation", "مقترح")],
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                ("message", models.TextField(max_length=5000, verbose_name="النص")),
                (
                    "customer_id",
                    models.PositiveBigIntegerField(verbose_name="رقم عميل EZYXS"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="اسم العميل"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=15, verbose_name="رقم التليفون"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("reviewing", "قيد المراجعة"),
                            ("closed", "مغلق"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإرسال"),
                ),
            ],
            options={
                "verbose_name": "طلب",
                "verbose_name_plural": "الطلبات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="feedback_su_status_440e7b_idx",
                    )
                ],
            },
        ),
    ]
