# Generated by Django 5.2.17 on 2026-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_id",
                    models.PositiveBigIntegerField(verbose_name="Youth center ID"),
                ),
                (
                    "facility_name",
                    models.CharField(max_length=100, verbose_name="Youth center"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("report", "Complaint"), ("recommendation", "Suggestion")],
                        max_length=20,
                        verbose_name="Request type",
                    ),
                ),
                ("message", models.TextField(max_length=5000, verbose_name="Message")),
                (
                    "customer_id",
                    models.PositiveBigIntegerField(verbose_name="EZYXS customer ID"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer name"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=15, verbose_name="Phone number"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email address"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Under review"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submitted at"),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="feedback_su_status_440e7b_idx",
                    )
                ],
            },
        ),
    ]
