# Generated by Django 5.2.17 on 2026-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="customer_id",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="رقم عميل EZYXS"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="اسم العميل"
            ),
        ),
    ]
