# Generated by Django 5.2.17 on 2026-10-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_require_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("staff_reply", "Staff reply"),
                    ("customer_reply", "Customer reply"),
                    ("archived", "Archived"),
                    ("status_changed", "Status changed"),
                ],
                max_length=20,
            ),
        ),
    ]
