TEXTS = {
    "ar": {
        "direction": "rtl",
        "site_title": "شكاوى ومقترحات مراكز الشباب",
        "page_title": "إرسال شكوى أو مقترح",
        "intro": "اختر مركز الشباب ونوع الطلب، ثم أدخل رقم هاتفك واكتب التفاصيل.",
        "facility": "مركز الشباب",
        "choose_facility": "اختر مركز الشباب",
        "category": "نوع الطلب",
        "choose_category": "اختر نوع الطلب",
        "report": "شكوى",
        "recommendation": "مقترح",
        "phone": "رقم الهاتف",
        "message": "تفاصيل الشكوى أو المقترح",
        "submit": "إرسال الطلب",
        "empty_facilities": "لا توجد مراكز شباب متاحة حاليًا. يُرجى المحاولة لاحقًا.",
        "missing_phone": "رقم الهاتف غير مرتبط بحساب عميل نشط في EZYXS.",
        "empty_message": "يرجى كتابة تفاصيل الطلب.",
        "invalid_phone": "أدخل رقم هاتف صحيحًا.",
        "success_title": "تم إرسال طلبك بنجاح",
        "reference": "رقم الطلب",
        "another": "إرسال طلب آخر",
        "unavailable_title": "الخدمة غير متاحة مؤقتًا",
        "unavailable_message": "تعذر الاتصال ببيانات EZYXS حاليًا. يُرجى المحاولة لاحقًا.",
        "language_link": "English",
    },
    "en": {
        "direction": "ltr",
        "site_title": "Youth Center Complaints and Suggestions",
        "page_title": "Submit a complaint or suggestion",
        "intro": "Select the youth center and request type, enter your phone number, and describe your request.",
        "facility": "Youth center",
        "choose_facility": "Select a youth center",
        "category": "Request type",
        "choose_category": "Select a request type",
        "report": "Complaint",
        "recommendation": "Suggestion",
        "phone": "Phone number",
        "message": "Complaint or suggestion details",
        "submit": "Submit request",
        "empty_facilities": "No youth centers are available right now. Please try again later.",
        "missing_phone": "This phone number is not linked to an active EZYXS customer account.",
        "empty_message": "Please describe your request.",
        "invalid_phone": "Enter a valid phone number.",
        "success_title": "Your request has been submitted",
        "reference": "Request number",
        "another": "Submit another request",
        "unavailable_title": "Service temporarily unavailable",
        "unavailable_message": "EZYXS data is currently unavailable. Please try again later.",
        "language_link": "العربية",
    },
}
